version: '3'

services:
    
    app:
        container_name: daily-pet-facts
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - "postgresql_pet_facts:postgresql_pet_facts"
        depends_on:
            - postgresql_pet_facts

    postgresql_pet_facts:
            container_name: postgresql_pet_facts
            image: postgres:14
            restart: always
            ports:
                - 5432:5432
            environment:
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
            volumes:
                - ./db/:/docker-entrypoint-initdb.d
                - pgdata:/var/lib/postgres/datadb

volumes:
    pgdata: